// src/data/articles/article-11.ts
import type { Article } from "./types";

export const article11: Article = {
  number: 11,
  title: "Emergency Powers",
  content: `
1.     No declaration of emergency may ever suspend, limit, or postpone the operation of any provision of this Constitution or the Charter of Rights and Freedoms, under any circumstances whatsoever.

2.     In the event of foreign invasion, declared war, or an imminent natural or technological catastrophe that manifestly threatens the physical survival of the nation or a major portion thereof, the executive may issue temporary operational orders limited strictly to the coordination of defence, evacuation, or life-saving measures.

3.     Every such order expires automatically after seventy-two hours unless ratified by a recorded, public, three-quarters vote of the elected House of the Republic, live-streamed to the people. No renewal may exceed seven days, and total duration may never exceed thirty days consecutively.

4.     Any citizen may challenge any operational order instantly before a special three-judge panel drawn by lot from the senior judiciary. The filing of such challenge automatically stays the challenged portion of the order pending the decision. The panel must hear the matter and render a binding decision within twenty-four hours. Frivolous or vexatious challenges, or challenges filed in manifest bad faith, shall expose the filer to summary contempt proceedings and a fine of up to three year’s median wage, payable to the public treasury.
      a)     No citizen challenge shall stay any operational order, or portion thereof, that the executive certifies in writing is immediately necessary to prevent loss of human life or catastrophic destruction of inhabited property during an active natural disaster (wildfire, flood, earthquake, volcanic eruption, hurricane, or equivalent event). In such cases the three-judge panel shall hear the challenge on an expedited basis and render a binding decision within six hours of filing, but the challenged measure remains fully in force until the panel rules. The panel may issue a stay only by unanimous vote and only upon finding that the measure is manifestly unrelated to the immediate preservation of life or inhabited property. Any citizen who knowingly files a frivolous or malicious challenge under this subsection that results in provable loss of life or destruction of inhabited property shall be guilty of depraved-indifference homicide and punished accordingly.
      b)     No citizen challenge may stay or delay any national emergency declaration triggered automatically by:
            i)      confirmed or credibly alleged deliberate tampering with the National Registry of Citizens or the National Registry of Qualified Experts; or
           ii)     any attack, sabotage, or degradation of the redundant physical or cryptographic backups of those registries.
            In such cases the emergency powers remain in full force until the Tribunal of Inquiry under section 5 has completed its report or until the Supreme Court, by unanimous vote of nine senior justices sitting en banc, certifies that no tampering or sabotage has occurred. The three-judge stay panel has no jurisdiction.

5.     Upon expiration, an automatic Tribunal of Inquiry composed of twelve citizens chosen by lot and three senior judges shall immediately convene and complete its investigation within sixty days. Any official found to have issued or ratified unnecessary, disproportionate, or fraudulent orders shall be guilty of high treason and punished accordingly under Article 15, with the penalty of death available for deliberate abuse that causes loss of life or liberty.

6.     No order issued under this Article may ever authorise the confiscation of firearms, the freezing of assets, the restriction of speech or assembly, the suspension of habeas corpus, or the imposition of medical mandates. Restriction of movement is permitted only within the immediate zone of physical danger and only for the duration of the manifest threat.
  `.trim(),

  precis: `
The idea that there can be a national emergency which warrants suspension of rights becomes absurd on the face of it. An emergency is when a meritocratic citizen’s rights are the most important to maintain.

Article 11 represents a pivotal safeguard in the Meritocratic Republic of Canada, explicitly designed to prevent the abuse of emergency powers that has historically enabled tyrannical overreach, as seen in recent global events where governments invoked crises to erode fundamental liberties under the guise of public safety. By prohibiting any suspension of the Constitution or Charter during emergencies, this provision ensures that core rights such as speech, self-defense, and property remain inviolable, even amid genuine threats like invasions or natural disasters, thereby securing the freedom of citizens to live without fear of arbitrary state expansion. In an age of advanced technology, where surveillance tools, AI-driven propaganda, and engineered crises could amplify governmental control, these strict limits counteract the perils of perpetual emergencies that dilute meritocratic governance, fostering instead a resilient society where excellence and individual agency prevail over collective panic.

Central to Article 11 is the emphasis on accountability and transparency, with automatic expirations, legislative ratification, and citizen challenges serving to prevent crimes like high treason through fraudulent declarations, which could otherwise lead to unwarranted seizures, mandates, or restrictions that undermine European-descended cultural continuity and national sovereignty. The provision’s mechanisms, including rapid judicial review and post-expiration tribunals, deter officials from exploiting emergencies for personal or ideological gain, addressing modern risks such as cyber-attacks on national registries or technological catastrophes that might be manipulated by supranational entities. By mandating public live-streaming and severe penalties for abuse, it promotes merit-based leadership, ensuring that only competent, principled individuals wield power, while protecting against the demographic and economic disruptions that unchecked authority has inflicted elsewhere.

Furthermore, by explicitly barring orders that confiscate arms, freeze assets, or impose medical interventions, Article 11 upholds the human experience of freedom in the face of future uncertainties, such as pandemics engineered through biotechnology or climate manipulations via geoengineering. This forward-looking stance preserves the European heritage of self-reliance and innovation that built Canada, preventing the crimes of eugenic control or population culling disguised as emergency measures, and guaranteeing that posterity inherits a nation where liberty is not negotiable. In safeguarding these elements, the Article fortifies the Republic against the vectors of tyranny amplified by 21st-century advancements, ensuring meritocracy thrives through vigilant, limited governance rather than expansive state dominance.
  `.trim(),
};