// src/data/articles/article-10.ts
import type { Article } from "./types";

export const article10: Article = {
  number: 10,
  title: "The Two Founding Peoples and Their Languages",
  content: `
Canada is a nation built by two founding European peoples, the English-speaking and the French-speaking, whose historic settlement, institutions, and sacrifices created the country that exists today.

1.     The French language and the distinct culture, civil-law tradition, and historic identity of Quebec shall be preserved and protected within the province of Quebec. No federal law or policy may impair the predominant use of French in public life, education, or signage in Quebec, nor suppress reasonable measures taken by the provincial government to maintain its French character.

2.     Reciprocally and with equal force, the English language and the historic culture and common-law tradition of the rest of Canada shall be preserved and protected in all provinces and territories outside Quebec. No provincial or federal law may impair the predominant use of English in public life, education, or signage in those jurisdictions.

3.     English and French are the sole official languages of Canada. All federal laws, regulations, and court proceedings shall be enacted and published in both languages. No other language may ever be granted official status at the federal level or be imposed on citizens in place of English or French.

4.     Nothing in this article shall be construed to permit censorship, forced bilingualism outside historic norms, or the elevation of any other culture or language above the two founding peoples.

5.     The national flag of the Republic of Canada shall be a new design that reflects the republican, European, and sovereign character of the nation. The House of the Republic shall enact the definitive flag within three years of ratification. No element of the royal arms of the United Kingdom or of the former Dominion of Canada may appear on the new flag. Until a new flag is enacted, the former 1965 Maple Leaf flag shall serve as a provisional flag for a period not exceeding three years from ratification.

6.     Only the national flag of the Republic and the recognised provincial flags may be flown on any public building, school, or government-funded institution. No foreign national flag, supranational flag, ideological banner, or corporate logo may be displayed on public property or above the national or provincial flag at any time. Private citizens remain free to fly any flag on their own property.
  `.trim(),

  precis: `
Article 10 honors the dual European heritage of Canada by recognizing the English-speaking and French-speaking peoples as the nation’s founding pillars, whose intertwined histories of exploration, settlement, and institution-building forged a prosperous society from a harsh wilderness. In an era of rapid globalization and digital homogenization, where languages and cultures can erode under the weight of mass migration and supranational influences, this provision is essential to safeguard the linguistic and cultural integrity that underpins national unity and meritocratic excellence. By protecting French predominance in Quebec and English elsewhere, it ensures that public life, education, and governance reflect the founders’ legacies, fostering environments where merit can flourish without the distortions of imposed multilingualism or cultural dilution. This approach secures the freedom of self-expression and continuity for future generations, preventing the existential crime of cultural genocide through gradual replacement, as witnessed in other nations where founding tongues have been marginalized by unchecked demographic shifts.

Central to Article 10 is the establishment of English and French as the sole official languages, prioritizing efficiency, clarity, and accessibility in federal affairs while rejecting the elevation of any other language that could fragment national cohesion. This exclusivity counters the modern threats of ideological agendas that weaponize diversity to impose burdensome policies, such as mandatory non-founding language requirements in public services, which have historically led to inefficiency, resentment, and reduced opportunities for competent citizens. By prohibiting forced bilingualism beyond historic norms and ensuring no other culture supersedes the founding ones, the Article prevents crimes like linguistic discrimination and the subversion of public institutions for partisan gain, promoting instead a society where excellence in communication drives progress. In the face of advancing AI translation tools and global media dominance, these safeguards maintain human-centered freedoms, allowing citizens to engage fully in governance without barriers erected by transient political fashions.

Furthermore, the mandate for a new republican flag and restrictions on public displays symbolize the Republic’s sovereign break from imperial remnants, reinforcing national pride and unity while warding off foreign or ideological encroachments on public spaces. This provision addresses contemporary perils such as corporate branding or supranational symbols infiltrating state institutions, which could undermine meritocratic values by prioritizing external loyalties over domestic achievement. By limiting flags on public property to national and provincial emblems, Article 10 secures the freedom of symbolic expression for private citizens while preventing the crimes of propaganda dissemination and visual pollution that erode public trust. In protecting these elements for the European posterity, it ensures Canada remains a resilient meritocracy, equipped to navigate future technological and geopolitical challenges without sacrificing the cultural foundations that enable true liberty and innovation.
  `.trim(),
};