// src/data/articles/article-28.ts
import type { Article } from "./types";

export const article28: Article = {
  number: 28,
  title: "Military Service, National Defence, and Policing",
  content: `
1.     The armed forces, the Ministry of War, of the Republic of Canada, exist solely to defend the territory, citizens, and Constitution of the Republic against all enemies, foreign and domestic. They shall never be deployed outside the territory of the Republic except in direct response to an attack upon Canadian soil or citizens, or in coalition with other nations of European descent facing existential threat. Under no circumstances shall the armed forces be deployed against any nation of European descent, nor shall they participate in any conflict that pits nations of European descent against one another.

2.     Every male citizen aged eighteen to forty-five is liable for military service. Service shall be compulsory for a period of twenty-four months between the ages of eighteen and twenty-five, unless exempted for verified physical or mental incapacity, or for conscientious objection limited to non-combat roles. Female citizens may volunteer on equal terms.

3.     The armed forces shall be maintained at a permanent minimum strength of 1.5 % of the citizen population under arms in peacetime, rising automatically to 4 % upon declaration of national emergency.

4.     The armed forces of the Republic shall maintain dedicated capabilities for the suppression of wildland fires threatening the territory, citizens, infrastructure, and ecological integrity of the nation. This mission includes procurement, maintenance, and operation of aerial water-bomber fleets, ground suppression units, and preventive fuel-management operations on public lands. During peacetime and compulsory service, personnel shall receive training in wildland firefighting techniques, aerial coordination, and environmental stewardship. Provincial authorities retain primary coordination of routine fire management, with military assets activated upon provincial request or national declaration when civilian resources are overwhelmed. Such fire-suppression forces may be deployed to foreign nations upon their request for humanitarian assistance in combating wildfires or similar natural disasters, without such deployment being construed as a military action or implying any threat to the recipient nation’s sovereignty.

5.     The Republic shall possess and maintain an independent nuclear deterrent sufficient to inflict unacceptable damage on any aggressor. The use of nuclear weapons is authorised only in response to nuclear, biological, chemical, or overwhelming conventional attack upon the Republic or its vital interests. No order to employ nuclear weapons may be issued unless confirmed in writing by the Prime Minister and by at least two ministers designated in advance by the House, each acting independently and from separate locations.

6.     The Prime Minister of the Republic is Commander-in-Chief. No military officer may obey an order that violates this Constitution. Every member of the armed forces swears allegiance exclusively to the Constitution and people of the Republic, never to any person or office.

7.     The Republic maintains armed neutrality toward all conflicts that do not directly threaten its territory or people. No standing military alliance may be joined unless approved by national referendum with a two-thirds majority.

8.     Every citizen has the right and duty to keep and bear arms under Article 3. In time of invasion or insurrection, all armed citizens are constituted as an unorganised militia under the command of the Prime Minister until regular forces can respond.

9.     The House of the Republic shall, by ordinary legislation reviewed at least every ten years, maintain contemporary forces, doctrines, and capabilities including but not limited to strategic and tactical nuclear forces, space, cyber, electromagnetic, unmanned, directed-energy, and counter-unmanned systems, sufficient to deter or defeat any conceivable adversary or combination of adversaries, and shall allocate from the sovereign wealth fund and debt-free public credit whatever resources are required for that purpose.

10.    Internal security and policing are divided as follows:
      a)     The Republic of Canada Mounted Police (RCMP) is the sole national police force with exclusive jurisdiction over:
            i)      high treason and crimes against the Constitution,
           ii)     organised crime crossing provincial boundaries,
          iii)    illicit drug manufacturing, trafficking, and importation,
           iv)     terrorism,
            v)     human trafficking and sexual exploitation,
           vi)     all forms of telecommunications, financial, and cryptographic fraud and scams,
          vii)    protection of the Prime Minister, ministers, judges, and critical national infrastructure.
            The RCMP shall maintain an elite, heavily armed, rapid-response capability and shall be granted full statutory authority to investigate and dismantle any criminal organisation exploiting Canadian citizens or territory.
      b)     Routine policing, traffic-law enforcement, provincial criminal code enforcement, and all other matters of public order remain the exclusive responsibility of provincial and municipal police services. Provinces may create or contract their own police forces but may never delegate policing powers to private corporations or foreign entities.

11.    No military or police force may ever be used against peaceful citizens exercising rights guaranteed by this Constitution. Any officer who issues or obeys an order to do so commits high treason.

12.    The Republic shall maintain such intelligence and counter-intelligence agencies as the House of the Republic deems necessary for the defence of the Constitution and the continued existence of the nation.
      a)     All intelligence agencies are subordinate to civilian authority, accountable to the Prime Minister and the House, and prohibited from any domestic surveillance of lawful political activity or speech.
      b)     Their organisation, methods, capabilities, and budgets shall be determined by ordinary legislation and revised as technology and threats evolve.
      c)     No offensive military deployment beyond the territory of the Republic may be ordered or commenced on the basis of an intelligence assessment that a foreign state or non-state actor has attacked the Republic or its citizens until that assessment has been subjected to an accelerated Special Tribunal of Review (modelled on Article 2) convened within 72 hours of the assessment being presented to the Prime Minister or the House. The Tribunal’s decision is binding, and any deployment commenced in violation of this section is unlawful.
      d)     Any intelligence officer or official who knowingly withholds, fabricates, or materially distorts evidence in such a proceeding commits high treason.
      e)     All raw intelligence data relevant to a claimed attack on the Republic shall be preserved in immutable form for no less than 100 years and made available to any future Tribunal of Inquiry. Access to the immutable archive for any future Tribunal or lawfully constituted inquiry shall not be subject to classification, executive privilege, or any other restriction except temporary redaction of still-active source identities, which shall automatically expire after 50 years.
  `.trim(),

  precis: `
Article 28 establishes a robust framework for military service, national defense, and policing that prioritizes the sovereignty and survival of the European-descended founding peoples, drawing from historical European traditions of disciplined citizen militias and strategic deterrence as exemplified in ancient Greek city-states and Swiss neutrality. This provision is essential because it transforms national defense from a bureaucratic apparatus into a merit-based duty, where compulsory service for able-bodied males fosters physical and mental resilience, practical skills like wildfire suppression, and a shared commitment to the nation’s integrity, securing the freedom to live in a secure homeland unthreatened by external aggression or internal subversion. By limiting deployments to direct threats or alliances with exclusively European-descent nations and explicitly prohibiting actions against such nations or in fratricidal conflicts, it prevents the wasteful entanglements in “brother wars” that have historically drained European resources and lives, averting crimes such as imperial overreach and the misuse of military power for supranational agendas that erode cultural continuity. In an era of advanced weaponry, cyber threats, and demographic pressures, this article safeguards against the tyranny of undefended borders or manipulated conflicts, ensuring that defense capabilities, including an independent nuclear deterrent, remain under strict constitutional checks to protect posterity’s right to a peaceful, self-determined existence.

This article also fortifies internal security through a clear division of policing powers, with the RCMP handling national threats like treason, organized crime, and human trafficking, while provinces manage routine order, thereby preventing the centralization of force that could enable authoritarian control or the privatization of justice that invites corruption. It secures freedoms by mandating allegiance solely to the Constitution, prohibiting the use of military or police against peaceful citizens, and embedding safeguards against intelligence abuses, such as mandatory tribunals for deployment decisions and immutable data archives, which thwart crimes like fabricated evidence leading to unjust wars or domestic surveillance that stifles dissent. Rooted in the European heritage of accountable governance, as seen in Magna Carta’s curbs on arbitrary power, these measures address modern risks like electromagnetic warfare and non-state actors, ensuring that policing enhances meritocratic society by targeting real harms such as drug trafficking and fraud without infringing on individual liberties or fostering dependency on foreign entities. The provision for deploying fire-suppression forces internationally on humanitarian grounds, without military implications, promotes goodwill and practical cooperation, reflecting a compassionate yet sovereign approach to global challenges like devastating wildfires.

Ultimately, Article 28 enhances the human experience of freedom by integrating defense and policing into a merit-driven system that prepares citizens for both martial and civic excellence, shielding future generations from the perils of weakness or overreach that have undermined nations in the technological age. It prevents genocidal threats through demographic displacement by maintaining armed neutrality and a capable force, aligning with the Charter’s emphasis on positive eugenics and cultural preservation to uphold the European founders’ legacy. In doing so, it promotes a republic where security bolsters prosperity, allowing individuals to thrive without the shadows of unchecked power or existential vulnerability.
  `.trim(),
};