// src/data/articles/article-04.ts
import type { Article } from "./types";

export const article4: Article = {
  number: 4,
  title: "Medical Freedom and the Healing Arts",
  content: `
1.     The practice of healing, whether conventional, complementary, or alternative, shall be regulated solely to prevent demonstrable fraud or immediate, provable physical danger to the patient.

2.     No practitioner, researcher, or healer may be deprived of licence, livelihood, or the right to offer treatment merely for employing or investigating methods that deviate from officially sanctioned doctrine or current medical consensus.

3.     Every person possesses absolute sovereignty over their own body. No person may be coerced by any means such as mandate, employment condition, restriction of movement, or otherwise into any medical examination, procedure, or pharmaceutical intervention against their will.

4.     The sovereignty of the person over their own body recognised in section 3 extends in full to minor children through the prior and unqualified right of their parents or legal guardians. No organ of the State, court, physician, hospital, child-protection agency, or any other entity may ever override or penalise parental medical decision-making for their minor children under any circumstances. The Republic recognises that parents, not the State, bear ultimate moral and legal responsibility for the life and well-being of their offspring.

5.     The security of the person includes the absolute right to bodily integrity and autonomy over one’s tissues, organs, and biological materials. No person shall be subjected to non-consensual harvesting, removal, donation, or commercialization of organs, placentas, or other bodily tissues under any circumstances, including but not limited to medical procedures, research, or posthumous procurement without explicit, revocable prior consent from the individual or their lawful next of kin. Coercion, undue influence, or presumption of consent is prohibited. Violations constitute a crime of force against the person, punishable as such.
  `.trim(),

  precis: `
In an epoch where pharmaceutical monopolies and institutional dogmas can suppress innovative therapies while mandating experimental interventions, Article 4 stands as a cornerstone of bodily autonomy in the Meritocratic Republic of Canada, affirming medical freedom as essential to the human experience of liberty and the advancement of the healing arts. This provision is paramount for accelerating medical, alternative, and complementary health regimens by positing that truth in health, discovered through unfettered exploration, is inherently beneficial, and that any societal tool enabling its pursuit while eradicating coercion is a fundamental good. Contrasted against historical suppressions, such as the persecution of herbalists in medieval Europe or, in modern times, the career-ending ostracism of doctors questioning mandates during global health crises, it prevents the crimes of intellectual and therapeutic stagnation that have impeded human well-being, honoring the European intellectual tradition of empirical inquiry from figures like Paracelsus and Hippocrates who challenged orthodoxy to heal. By limiting regulation solely to fraud or immediate danger and protecting practitioners from licensure loss over deviant methods, it secures the liberty of citizens to pursue holistic health without fear. In contemporary landscapes, where corporate capture and digital surveillance threaten personal sovereignty, this Article safeguards the human experience of freedom by ensuring that merit, not consensus, dictates healing practices, thereby promoting health knowledge and preserving the founders’ legacy of rational self-determination against forces that commodify the body.

The absolute sovereignty over one’s body, extending to parental authority over minors, prohibits coercion into any medical procedure, echoing meritocratic principles by entrusting competent individuals with decisions that align with their values. This framework prevents abuses like forced sterilizations or non-consensual organ harvesting that have marred history, mandating altruistic donations overseen by merit-based tribunals and banning commercialization to uphold dignity, while classifying violations as crimes of force or fraud punishable by imprisonment and fines. By recognizing parents’ unqualified right to direct their children’s medical care without state override, it draws from European familial traditions of guardianship, countering modern perils such as ideological indoctrination in schools or hospitals that could erode family integrity. This forward-thinking structure not only shields practitioners and patients but also fortifies national health, addressing twenty-first-century threats like bioengineering ethics or pandemic overreach that might otherwise undermine the Republic’s commitment to flourishing, merit-proven citizens.

Central to Article 4 is an unwavering faith in the individual’s capacity to discern what is best for their own body through informed choice, for if citizens cannot be entrusted with medical autonomy, then the essence of personal responsibility and human dignity dissolves. History warns that paths of mandated medicine lead inexorably to tyranny, as seen in regimes that equated refusal to compliance as societal harm. No authority can be safely empowered to override bodily integrity, for it invites endless encroachments where health decisions are reframed as collective duties; thus, medical freedom must remain inviolable, rooted in the conviction that truth in healing is good, just as with speech and inquiry. Furthermore, the Article provides robust protections for healers and patients, limiting penalties to proven fraud while shielding good-faith innovators from ruinous repercussions, encouraging bold exploration without fear of licensure revocation, paving the way for a meritocratic future where health emerges from free, protected choices, preserving the European character of the nation against coercive threats.
  `.trim(),
};